### ISSUE TITLE
toil.jobStores.abstractJobStore.NoSuchFileException: File 'config.pickle' does not exist.

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#833] opened 2022-11-08 14:55 UTC
Dear developer:
We are testing your instance file, but we find it is not working properly. How can you solve this problem?
Thank you!

/home/lidong/Software/cactus-v2.2.4/cactus_env/bin/cactus-minigraph ./ 5-cow-pg.txt cow-pg.gfa.gz --reference bosTau9 --logFile cow-pg-minigraph.log --batchSystem mesos --defaultPreemptable --nodeType r5.8xlarge:1.5 --nodeStorage 650 --maxNodes 25 --betaInertia 0 --targetTime 1 --mapCores 16 --workDir ./new2/ --restart
[2022-11-08T22:53:45+0800] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2022-11-08T22:53:45+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/lidong/Software/cactus-v2.2.4/cactus_env/bin/cactus-minigraph ./ 5-cow-pg.txt cow-pg.gfa.gz --reference bosTau9 --logFile cow-pg-minigraph.log --batchSystem mesos --defaultPreemptable --nodeType r5.8xlarge:1.5 --nodeStorage 650 --maxNodes 25 --betaInertia 0 --targetTime 1 --mapCores 16 --workDir ./new2/ --restart
[2022-11-08T22:53:45+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: b699f6bfb4fe88b7876e533dede24e48bbfeb700
Traceback (most recent call last):
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 661, in read_shared_file_stream
    with open(self._get_shared_file_path(shared_file_name), 'rb' if encoding == None else 'rt', encoding=encoding, errors=errors) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lidong/Data/05.pangenome/22.Minigraph_cactus/files/shared/config.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/bin/cactus-minigraph", line 8, in <module>
    sys.exit(main())
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_minigraph.py", line 74, in main
    with Toil(options) as toil:
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/lib/python3.8/site-packages/toil/common.py", line 875, in __enter__
    jobStore.resume()
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 119, in resume
    super().resume()
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/lib/python3.8/site-packages/toil/jobStores/abstractJobStore.py", line 213, in resume
    with self.read_shared_file_stream('config.pickle') as fileHandle:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/lidong/Software/cactus-v2.2.4/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 666, in read_shared_file_stream
    raise NoSuchFileException(shared_file_name)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'config.pickle' does not exist.

**Comment by glennhickey** [comment] 2022-11-08 15:23
This seems to be a duplicate of #832 (side-effect of using mesos outside proper aws environment)

**Closed by glennhickey** 2022-11-08 15:23 UTC
