### ISSUE TITLE
Missing genomes in output

### ISSUE THREAD

**Issue by zwuckl** [ComparativeGenomicsToolkit/cactus#143] opened 2020-02-12 08:20 UTC
Hey folks,

I'm trying to use Cactus to align a handful of genomes from the same plant family using "--binariesMode local" within a Singularity instance which I've used before and which ran the "evolverMammals" example perfectly. 

Despite Cactus ending successfully, the final HAL output only comprises alignments for 2 (plus their ancestor) out of the 9 genomes I put in. Since I've aligned some of the genomes before in a different context, I know that there are extensive homologous regions and I'd expect massive multiple alignments. 

To nail the problem down, I've rerun the pipeline inputting only one sequence per genome that share homologous stretches and that Cactus successfully aligned about a year ago in a different setup.

My test input file looks like this, with paths according to the mount point within Singularity:
```
(funhy,((((phyeuA,phyeuB),phyeuNA),((phypyA,phypyB),phypyNA)),(phypa,physp)));
funhy /home/cactus/Funhy.softmasked.fa
phyeuA /home/cactus/PhyeuA.softmasked.fa
phyeuB /home/cactus/PhyeuB.softmasked.fa
phyeuNA /home/cactus/PhyeuNA.softmasked.fa
*phypa /home/cactus/Phypa.softmasked.fa
phypyA /home/cactus/PhypyA.softmasked.fa
phypyB /home/cactus/PhypyB.softmasked.fa
phypyNA /home/cactus/PhypyNA.softmasked.fa
physp /home/cactus/Physp.softmasked.fa
```

I run Cactus as follows:
```
$ singularity exec --cleanenv --home /nfs/scratch/nico.vangessel/Funariaceae/wga/cactus/test:/home/cactus --bind /nfs/scratch/nico.vangessel/Funariaceae/wga/cactus/singularity_tmp/:/tmp ../cactus2020.simg cactus --workDir=/home/cactus/work --binariesMode local --logFile /home/cactus/test.log --maxCores 16 --logDebug /home/cactus/jobStore /home/cactus/test.txt /home/cactus/test.hal
```

halStats (and hal2maf) only report "(phypyA:1,phypyB:1)Anc7;":
```
hal v2.1
(phypyA:1,phypyB:1)Anc7;

GenomeName, NumChildren, Length, NumSequences, NumTopSegments, NumBottomSegments
Anc7, 2, 357851, 4, 0, 3037
phypyA, 0, 67070, 1, 2496, 0
phypyB, 0, 339743, 1, 1021, 0
```

Do you have any clue on what's going on here? Any help is much appreciated and I will gladly upload my log file on request.

Since I thought it might be related to the tree topology, I'm trying to repeat the run without those two genomes, "phypyA" and "phypyB", to see what's happening with the rest of my genomes when these are not present.

Thanks,
Nico

**Comment by glennhickey** [comment] 2020-02-12 13:47
Hi, I think this is a bug that appeared in master for a while and has since been fixed (see discussion [here](https://github.com/ComparativeGenomicsToolkit/hal/issues/98#issuecomment-579837387)).  

I'm not sure what state the current master is in, and suggest using this version:
https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/LAST_PYTHON2_SUPPORT

with python 2.7 and toil 3.20.0 for now.

**Comment by zwuckl** [comment] 2020-02-13 10:02
Hi Glenn,
thanks a lot for your super fast response!

I downloaded the tagged release but am now facing problems with building the Docker image following Nathan's guide in https://github.com/ComparativeGenomicsToolkit/cactus/issues/94
It seems there are some components that are upgraded during the build process (such as `more-itertools`) and thereby become incompatible to Python 2.7. 

I don't know if this topic is still right for such a discussion, but would you recommend trying to fix the dependency issues? Or try my luck building a Python 3 Cactus Docker image (is there an official recipe yet?)?

**Comment by glennhickey** [comment] 2020-02-14 12:53
We should have Python3 support in the Cactus master branch any day now.
Once that's done I'll try adding / supporting Nathan's Dockerfile within
the repo -- there's clearly demand for it!  Thanks for your patience

**Comment by glennhickey** [comment] 2020-02-14 12:56
Looks like Python3 support was merged in last night.  It might be worth
trying again with the current master -- I'll still take a look at getting
that Dockerfile in.

**Comment by zwuckl** [comment] 2020-02-17 08:29
Thanks for the update on Python 3, Glenn. In the meantime I was able to get the Docker image working with the `LAST_PYTHON2_SUPPORT` version of Cactus. Here's my modified Dockerfile:

```
FROM ubuntu:xenial-20191108 AS builder

RUN apt-get update && apt-get install --no-install-recommends -y git gcc g++ build-essential python-dev zlib1g-dev libkyototycoon-dev libtokyocabinet-dev libkyotocabinet-dev libbz2-dev pkg-config python-pip python-setuptools python-wheel

ENV kyotoTycoonIncl -I/usr/include -DHAVE_KYOTO_TYCOON=1
ENV kyotoTycoonLib -L/usr/lib -Wl,-rpath,/usr/lib -lkyototycoon -lkyotocabinet -lz -lbz2 -lpthread -lm -lstdc++
RUN mkdir -p /home/cactus

COPY . /home/cactus

RUN python -V
RUN pip -V

RUN cd /home/cactus && make clean && rm -f /home/cactus/submodules/hdf5/bin/h5c++
RUN cd /home/cactus && make

RUN pip install --upgrade --prefix=/home/cactus/.local toil==3.20.0
RUN pip install --upgrade --prefix=/home/cactus/.local setuptools
RUN pip install --prefix=/home/cactus/.local https://github.com/erikrose/more-itertools/releases/download/5.0.0/more_itertools-5.0.0-py2-none-any.whl
RUN pip install --upgrade --prefix=/home/cactus/.local zipp==1.1.0
RUN pip install --upgrade --prefix=/home/cactus/.local pytest==4.6.9
# https://github.com/ComparativeGenomicsToolkit/cactus/pull/79
RUN cd /home/cactus && sed -i.bak 's/networkx>=2,<3/networkx==2.2/' setup.py && pip install --upgrade --prefix=/home/cactus/.local .

FROM ubuntu:xenial-20191108
RUN apt-get update && apt-get install --no-install-recommends -y kyototycoon libtokyocabinet9 python python-pytest zlib1g bzip2 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /home/cactus/bin/* /usr/local/bin/
COPY --from=builder /home/cactus/submodules/sonLib/bin/* /usr/local/bin/
COPY --from=builder /home/cactus/submodules/cactus2hal/bin/* /usr/local/bin/
COPY --from=builder /home/cactus/.local/bin/* /usr/local/bin/
# /usr/local/lib/python2.7/site-packages not in sys.path
COPY --from=builder /home/cactus/.local/lib/python2.7/site-packages/ /usr/local/lib/python2.7/dist-packages/

# https://github.com/ComparativeGenomicsToolkit/cactus/issues/102#issuecomment-540781259
RUN sed -i'' -n '/config.writeXML/d; p' /usr/local/lib/python2.7/dist-packages/cactus/progressive/cactus_createMultiCactusProject.py
```

For the specific version of `more-itertools`, `zipp` and `pytest` to be kept during the updating process, I also modified the `install_requires` part of `setup.py` file within the Cactus dir:

```python
from setuptools import setup, find_packages
import os
import subprocess

versionFile = "src/cactus/shared/version.py"
if os.path.exists(versionFile):
    os.remove(versionFile)
git_commit = subprocess.check_output(['git', 'rev-parse', 'HEAD']).strip()
with open(versionFile, 'w') as versionFH:
    versionFH.write("cactus_commit = '%s'\n" % git_commit)


setup(
    name="progressiveCactus",
    version="1.0",
    author="Benedict Paten",
    package_dir = {'': 'src'},
    packages=find_packages(where='src'),
    include_package_data=True,
    package_data={'cactus': ['*_config.xml']},
    # We use the __file__ attribute so this package isn't zip_safe.
    zip_safe=False,

    install_requires=[
        'decorator',
        'subprocess32',
        'psutil',
        'networkx>=2,<3',
        'cython',
        'pytest==4.6.9',
        'more-itertools==5.0.0',
        'zipp==1.1.0',
        # Someone uploaded an old version of sonLib to pyPI, so we have to use this name
        'actualSonLib'],

    entry_points={
        'console_scripts': ['cactus = cactus.progressive.cactus_progressive:main',
                            'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
```

**Comment by glennhickey** [comment] 2020-02-18 21:30
Cool!  I just tried to make an adaptation of the current Docker in master to do something equivalent but it doesn't seem straightforward to set up python3.6 in Ubuntu 16.04.  May be wisest to move to 18.04 in Docker even if that means getting kyoto from github instead of apt.  Will try to see if I can get it to work.

**Comment by diekhans** [comment] 2020-02-19 00:12
You can tell apt-get to use the older packages to get kyoto.  I
figure it out once, ping me if you have problems.

**Comment by glennhickey** [comment] 2020-02-19 18:07
@diekhans Yes! I would be very curious to see how you're building cactus on 18.04 with kyoto apt!  

I just tried by copying https://gist.githubusercontent.com/rohitrawat/60a04e6ebe4a9ec1203eac3a11d4afc1/raw/fcdfde2ab57e455ba9b37077abf85a81c504a4a9/sources.list into `/etc/apt/sources.list.d/xeniallist` and changing `us.archive.ubuntu.com` to just `archive.ubuntu.com` but I still get the same old errors:
```
g++  -O3 -g -Wall -funroll-loops -DNDEBUG -I/usr/include -DHAVE_TOKYO_CABINET=1 -I/usr/include -DHAVE_KYOTO_TYCOON=1    -I../externalTools/quicktree_1.1/include/ -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -DHAVE_REDIS=1 -I inc -I ../lib/ -c impl/*.cpp
In file included from /usr/include/ktremotedb.h:25:0,
                 from impl/sonLibKVDatabase_KyotoTycoon.cpp:36:
/usr/include/ktulog.h:51:23: error: 'constexpr' needed for in-class initialization of static data member 'const double kyototycoon::UpdateLogger::FLUSHWAIT' of non-integral type [-fpermissive]
   static const double FLUSHWAIT = 0.1;
                       ^~~~~~~~~
In file included from impl/sonLibKVDatabase_KyotoTycoon.cpp:36:0:
/usr/include/ktremotedb.h: In member function 'char* kyototycoon::RemoteDB::Cursor::get_key(size_t*, bool)':
/usr/include/ktremotedb.h:301:16: error: cannot convert 'bool' to 'char*' in return
         return false;
                ^~~~~
/usr/include/ktremotedb.h: In member function 'char* kyototycoon::RemoteDB::Cursor::get_value(size_t*, bool)':
/usr/include/ktremotedb.h:353:16: error: cannot convert 'bool' to 'char*' in return
         return false;
                ^~~~~
/usr/include/ktremotedb.h: In member function 'char* kyototycoon::RemoteDB::Cursor::get(size_t*, const char**, size_t*, int64_t*, bool)':
/usr/include/ktremotedb.h:414:16: error: cannot convert 'bool' to 'char*' in return
         return false;
                ^~~~~
/usr/include/ktremotedb.h: In member function 'char* kyototycoon::RemoteDB::Cursor::seize(size_t*, const char**, size_t*, int64_t*)':
/usr/include/ktremotedb.h:484:16: error: cannot convert 'bool' to 'char*' in return
         return false;
                ^~~~~
Makefile:55: recipe for target '../lib/sonLib.a' failed
make[3]: Leaving directory '/home/cactus/submodules/sonLib/C'
make[3]: *** [../lib/sonLib.a] Error 1
make[2]: *** [cP] Error 2
Makefile:14: recipe for target 'cP' failed
make[2]: Leaving directory '/home/cactus/submodules/sonLib'
Makefile:137: recipe for target 'suball.sonLib' failed
make[1]: Leaving directory '/home/cactus'
make[1]: *** [suball.sonLib] Error 2
Makefile:32: recipe for target 'all' failed
make: *** [all] Error 2
```

Presumably because the 18.04 compiler is too new for this version.

**Comment by diekhans** [comment] 2020-02-19 18:41
Try -std=c++11

**Comment by glennhickey** [comment] 2020-02-19 19:22
That doesn't work.  `static const double FLUSHWAIT = 0.1;` is illegal in C++11.  It requires `constexpr` as the error says.  Going back to an older standard with `-std=c++03` fails with
```
gcc -std=c99 -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG  -I/usr/include -DHAVE_TOKYO_CABINET=1 -I/usr/include -DHAVE_KYOTO_TYCOON=1    -I../externalTools/quicktree_1.1/include/ -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -DHAVE_REDIS=1 -I inc -I ../lib/  -c impl/*.c
g++ -std=c++03   -O3 -g -Wall -funroll-loops -DNDEBUG -I/usr/include -DHAVE_TOKYO_CABINET=1 -I/usr/include -DHAVE_KYOTO_TYCOON=1    -I../externalTools/quicktree_1.1/include/ -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -DHAVE_REDIS=1 -I inc -I ../lib/ -c impl/*.cpp
In file included from /usr/include/ktcommon.h:24:0,
                 from /usr/include/ktremotedb.h:19,
                 from impl/sonLibKVDatabase_KyotoTycoon.cpp:36:
/usr/include/kcdbext.h: In member function 'char* kyotocabinet::IndexDB::get(const char*, size_t, size_t*)':
/usr/include/kcdbext.h:1281:14: error: 'nullptr' was not declared in this scope
       return nullptr;
              ^~~~~~~
make[3]: *** [../lib/sonLib.a] Error 1

```

**Comment by diekhans** [comment] 2020-02-19 19:45
Hmm, I think  this is why I gave up on getting it to compile,

Doing a
  #define nullptr NULL

before including the header might work with -std=c++03.

Have you tried the 'maintained' version:  https://github.com/carlosefr/kyoto

**Comment by nathanweeks** [comment] 2020-02-24 21:57
FWIW, here's an update Python 2 Dockerfile, which replaces most of the pip-installed packages with Ubuntu package equivalents (which should facilitate a more-reproducible build, as their versions are pinned according to the Ubuntu release):

```
# https://github.com/ComparativeGenomicsToolkit/cactus/issues/94
FROM ubuntu:xenial-20200212 AS builder
# for some reason archive.ubuntu.com hangs...
#RUN sed -i'' 's#http://archive.ubuntu.com/ubuntu/#http://mirror.math.princeton.edu/pub/ubuntu/#' /etc/apt/sources.list

RUN apt-get update && apt-get install --no-install-recommends -y \
  build-essential \
  cython \
  g++ \
  gcc \
  git \
  libbz2-dev \
  libhdf5-cpp-11 \
  libhdf5-dev \
  libkyotocabinet-dev \
  libkyototycoon-dev \
  libtokyocabinet-dev \
  pkg-config \
  python-dev \
  python-dateutil \
  python-future \
  python-pip \
  python-psutil \
  python-pytest \
  python-requests \
  python-six \
  python-setuptools \
  python-subprocess32 \
  python-wheel \
  zlib1g-dev \
  wget

ENV kyotoTycoonIncl -I/usr/include -DHAVE_KYOTO_TYCOON=1
ENV kyotoTycoonLib -L/usr/lib -Wl,-rpath,/usr/lib -lkyototycoon -lkyotocabinet -lz -lbz2 -lpthread -lm -lstdc++
RUN mkdir -p /home/cactus

COPY . /home/cactus

#RUN cd /home/cactus && make clean
RUN cd /home/cactus && make

RUN pip install toil==3.24.0

# https://github.com/ComparativeGenomicsToolkit/cactus/pull/79
RUN cd /home/cactus && sed -i.bak 's/networkx>=2,<3/networkx==2.2/' setup.py && pip install .

FROM ubuntu:xenial-20200212
#RUN sed -i'' 's#http://archive.ubuntu.com/ubuntu/#http://mirror.math.princeton.edu/pub/ubuntu/#' /etc/apt/sources.list
RUN apt-get update && apt-get install --no-install-recommends -y \
  bzip2 \
  cython \
  kyototycoon \
  libhdf5-cpp-11 \
  libtokyocabinet9 \
  python \
  python-dateutil \
  python-future \
  python-psutil \
  python-pytest \
  python-requests \
  python-six \
  python-subprocess32  \
  zlib1g \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/ /home/cactus/bin/ /home/cactus/submodules/sonLib/bin/ /home/cactus/submodules/cactus2hal/bin/ /usr/local/bin/
COPY --from=builder /usr/local/lib/python2.7/dist-packages/ /usr/local/lib/python2.7/dist-packages/

# https://github.com/ComparativeGenomicsToolkit/cactus/issues/102#issuecomment-540781259
RUN sed -i'' -n '/config.writeXML/d; p' /usr/local/lib/python2.7/dist-packages/cactus/progressive/cactus_createMultiCactusProject.py
```

This Dockerfile assumes a cactus commit just a bit beyond the LAST_PYTHON2_SUPPORT tag:
```
git checkout c950f037cabddc798ae5d5d2062f098ea218ceca
git submodule update --init --recursive
docker build -t cactus:c950f0 Dockerfile.complete .
```

Two caveats:
1. I'm encountering https://github.com/ComparativeGenomicsToolkit/cactus/issues/119 when exporting the resulting Docker image to Singularity (using [docker2singularity](https://quay.io/repository/singularity/docker2singularity)) and running it on our HPC cluster
2. This Dockerfile doesn't install dependencies for all the "fixin's" (e.g., hal2assemblyHub.py needs jobTree)

But maybe it this could supply some ideas as far as crafting a Dockerfile that results in a more reproducible build...

**Comment by glennhickey** [comment] 2020-02-24 22:19
It's definitely useful.  I'm hoping this sort of thing will get easier once #148 is merged in.  It has a [Dockerfile](https://github.com/ComparativeGenomicsToolkit/cactus/blob/bring-back-kyoto-submodule/Dockerfile) based on a more modern ubuntu image, and works with the latest cactus.  Once that's in we'll get a version based on your work that can actually run the whole pipeline onto github.  

For reproducibility, I understand that it would be valuable to get these Dockefiles tied to specific cactus versions.  I'm not too sure what's the best mechanism to use for this.  Perhaps just a folder with Dockerfile.v1, Dockerfile.v2 etc?  One alternative is to rely on github, but then it's kind of difficult to pull out specific dockerfiles that way.

**Comment by nathanweeks** [comment] 2020-02-25 17:41
@glennhickey : Thanks for the update! Getting the Python 3 version working with a modern Ubuntu would be great.

Regarding reproducibility: at least starting out, I think it would be useful to have a Dockerfile that builds the version of cactus as it exists at that commit in the Git repo (including submodules). As a bonus, this could perhaps be used to facilitate continuous integration testing, and tagged releases could be published on Docker Hub using [automated builds](https://docs.docker.com/docker-hub/builds/).

**Comment by glennhickey** [comment] 2020-03-19 19:07
Closing this, as the original missing genomes issue was fixed a while back (by updating the HAL submodule).  

Hopefully the new [Cactus Dockerfile](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile) addresses the subsequent discussion..

**Closed by glennhickey** 2020-03-19 19:07 UTC
