### ISSUE TITLE
Deadlock Exception on examples/evolverMammals.txt

### ISSUE THREAD

**Issue by ShoumikSaha** [ComparativeGenomicsToolkit/cactus#223] opened 2020-04-25 01:11 UTC
After successfully installing cactus through miniconda, I tried to check my setup by genomes from examples/evolverMammals.txt
After running for almost an hour, it raises a **Deadlock Exception**.
"_raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException: Deadlock encountered: The system is service deadlocked - all 2 running jobs are active services_"

I'm attaching the last part of the log file here-
[log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4532134/log.txt)

**Comment by glennhickey** [comment] 2020-04-25 15:59
Duplicate of #150.  As in that one, you'll need to run with `--logDebug` to find out which resource you're running out of (disk space or RAM) that's causing the deadlock.  We're hopefully going to make Toil's error message from more clear in the future: https://github.com/DataBiosphere/toil/issues/3016

**Closed by glennhickey** 2020-04-25 15:59 UTC
