### ISSUE TITLE
Unsure as to what this error means

### ISSUE THREAD

**Issue by ndtvchris** [ComparativeGenomicsToolkit/cactus#666] opened 2022-02-15 20:03 UTC
Hello again,

I tried spinning up a larger Docker container which seemed to have passed the resource check, but then the process ended and I cannot seem to decipher the reason why. Attached is a picture.

Thank you as always.

Sincerely,
Chris
[Another cactus error.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/8074270/Another.cactus.error.txt)

**Comment by glennhickey** [comment] 2022-02-15 21:00
Duplicate of #574.  I really need to make a more informative error message for this!

**Closed by glennhickey** 2022-02-15 21:00 UTC
