### ISSUE TITLE
cactus-graphmap-join error

### ISSUE THREAD

**Issue by ETC100** [ComparativeGenomicsToolkit/cactus#1001] opened 2023-04-25 04:34 UTC
Hello, I tried to run the last step to construct the graph pan-genome and a error occured.
Command I used:  cactus-graphmap-join ./jobstore --vg Result/chrom-alignments/*.vg --hal Result/chrom-alignments/*.hal --outDir Result --outName species_graph --reference REF --workDir ./ --vcf clip filter --giraffe clip filter
Cactus version: 2.5.1
A total of 12 tasks were reported to have the same error. It seems that 12 vg files were failed in this process because of the ascii codec error. So I chose one small vg file with error and uploaded (https://drive.google.com/file/d/1i9cT393rp-tsLUyuUlfO_9jXbSBFBP5_/view?usp=sharing).
The log was as followed:

> [2023-04-25T11:45:24+0800] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/bin/cactus-graphmap-join", line 8, in <module>
    sys.exit(main())
  File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap_join.py", line 99, in main
    graphmap_join(options)
  File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap_join.py", line 241, in graphmap_join
    wf_output = toil.start(Job.wrapJobFn(graphmap_join_workflow, options, config, vg_ids, hal_ids))
  File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1030, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1470, in _runMainLoop
    return Leader(config=self.config,
  File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 330, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/home/my_folder/srr/species-genome/jobstore' contains 12 failed jobs: 'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v6, 'vg_clip_vg' kind-vg_clip_vg/instance-6lb785sc v6, 'graphmap_join_workflow' kind-graphmap_join_workflow/instance-nn_wr80k v2, 'vg_clip_vg' kind-vg_clip_vg/instance-0i20ih8z v6, 'Job' kind-Job/instance-sehroahk v2, 'vg_clip_vg' kind-vg_clip_vg/instance-6s8baebq v6, 'vg_clip_vg' kind-vg_clip_vg/instance-3k_h80t3 v6, 'Job' kind-Job/instance-ocwjjjpr v2, 'vg_clip_vg' kind-vg_clip_vg/instance-nis10xst v6, 'vg_clip_vg' kind-vg_clip_vg/instance-5kol84g4 v6, 'Job' kind-Job/instance-2cpnasiz v2, 'join_vg' kind-join_vg/instance-z32hdrzf v3
Log from job "'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v6" follows:
=========>
        [2023-04-25T10:19:18+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-04-25T10:19:18+0800] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host 191.48.2.10.cau.edu.cn.
        [2023-04-25T10:19:18+0800] [MainThread] [I] [toil.worker] Working on job 'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v4
        [2023-04-25T10:19:19+0800] [MainThread] [I] [toil.worker] Loaded body Job('vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v4) from description 'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v4
        [2023-04-25T10:19:19+0800] [MainThread] [W] [toil.fileStores.nonCachingFileStore] Starting job files/for-job/kind-vg_clip_vg/instance-cw1aggx2/cleanup/file-cc6c92a440474d7d97d47ba707365488/stream with less than 10%% of disk space remaining.
        [2023-04-25T10:19:19+0800] [MainThread] [I] [cactus.shared.common] Running the command ['bash', '-c', 'set -eo pipefail && vg clip /home/my_folder/srr/species-genome/e680534b68e95b469e877a219b671356/75c7/0165/tmp5e1lh10z/NC_006090.5.vg -d 2 -P REF -m 1000 | vg clip -d 1 - -P REF | vg clip -s - -P REF']
        [2023-04-25T10:19:19+0800] [MainThread] [I] [toil-rt] 2023-04-25 10:19:19.338537: Running the command: "bash -c set -eo pipefail && vg clip /home/my_folder/srr/species-genome/e680534b68e95b469e877a219b671356/75c7/0165/tmp5e1lh10z/NC_006090.5.vg -d 2 -P REF -m 1000 | vg clip -d 1 - -P REF | vg clip -s - -P REF"
        [2023-04-25T10:24:55+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-04-25T10:24:55+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-clip_vg/instance-7fbonoq0/file-db041cc7e6824a8d842f7a8f268c2e27/NC_006090.5.vg.clip' to path '/home/my_folder/srr/species-genome/e680534b68e95b469e877a219b671356/75c7/0165/tmp5e1lh10z/NC_006090.5.vg'
        Traceback (most recent call last):
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2743, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2660, in _run
raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/home/my_folder/srr/species-genome/jobstore' contains 12 failed jobs: 'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v6, 'vg_clip_vg' kind-vg_clip_vg/instance-6lb785sc v6, 'graphmap_join_workflow' kind-graphmap_join_workflow/instance-nn_wr80k v2, 'vg_clip_vg' kind-vg_clip_vg/instance-0i20ih8z v6, 'Job' kind-Job/instance-sehroahk v2, 'vg_clip_vg' kind-vg_clip_vg/instance-6s8baebq v6, 'vg_clip_vg' kind-vg_clip_vg/instance-3k_h80t3 v6, 'Job' kind-Job/instance-ocwjjjpr v2, 'vg_clip_vg' kind-vg_clip_vg/instance-nis10xst v6, 'vg_clip_vg' kind-vg_clip_vg/instance-5kol84g4 v6, 'Job' kind-Job/instance-2cpnasiz v2, 'join_vg' kind-join_vg/instance-z32hdrzf v3
Log from job "'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v6" follows:
=========>
        [2023-04-25T10:19:18+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-04-25T10:19:18+0800] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host 191.48.2.10.cau.edu.cn.
        [2023-04-25T10:19:18+0800] [MainThread] [I] [toil.worker] Working on job 'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v4
        [2023-04-25T10:19:19+0800] [MainThread] [I] [toil.worker] Loaded body Job('vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v4) from description 'vg_clip_vg' kind-vg_clip_vg/instance-cw1aggx2 v4
        [2023-04-25T10:19:19+0800] [MainThread] [W] [toil.fileStores.nonCachingFileStore] Starting job files/for-job/kind-vg_clip_vg/instance-cw1aggx2/cleanup/file-cc6c92a440474d7d97d47ba707365488/stream with less than 10%% of disk space remaining.
        [2023-04-25T10:19:19+0800] [MainThread] [I] [cactus.shared.common] Running the command ['bash', '-c', 'set -eo pipefail && vg clip /home/my_folder/srr/species-genome/e680534b68e95b469e877a219b671356/75c7/0165/tmp5e1lh10z/NC_006090.5.vg -d 2 -P REF -m 1000 | vg clip -d 1 - -P REF | vg clip -s - -P REF']
        [2023-04-25T10:19:19+0800] [MainThread] [I] [toil-rt] 2023-04-25 10:19:19.338537: Running the command: "bash -c set -eo pipefail && vg clip /home/my_folder/srr/species-genome/e680534b68e95b469e877a219b671356/75c7/0165/tmp5e1lh10z/NC_006090.5.vg -d 2 -P REF -m 1000 | vg clip -d 1 - -P REF | vg clip -s - -P REF"
        [2023-04-25T10:24:55+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-04-25T10:24:55+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-clip_vg/instance-7fbonoq0/file-db041cc7e6824a8d842f7a8f268c2e27/NC_006090.5.vg.clip' to path '/home/my_folder/srr/species-genome/e680534b68e95b469e877a219b671356/75c7/0165/tmp5e1lh10z/NC_006090.5.vg'
        Traceback (most recent call last):
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2743, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2660, in _run
            return self.run(fileStore)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2888, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap_join.py", line 524, in vg_clip_vg
            cactus_call(parameters=clip_cmd, outfile=clipped_path)
          File "/home/my_folder/biosoft/cactus-bin-v2.5.1/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 772, in cactus_call
            output, stderr = process.communicate(stdin_string if first_run else None, timeout=10)
          File "/home/my_folder/anaconda3/envs/graph_genome/lib/python3.8/subprocess.py", line 1028, in communicate
            stdout, stderr = self._communicate(input, endtime, timeout)
          File "/home/my_folder/anaconda3/envs/graph_genome/lib/python3.8/subprocess.py", line 1910, in _communicate
            stderr = self._translate_newlines(stderr,
          File "/home/my_folder/anaconda3/envs/graph_genome/lib/python3.8/subprocess.py", line 905, in _translate_newlines
	data = data.decode(encoding, errors)
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 257: ordinal not in range(128)

**Comment by glennhickey** [comment] 2023-04-25 13:38
Not to sure what's going on here.  I was unable to reproduce (my [log is here](https://github.com/ComparativeGenomicsToolkit/cactus/files/11323036/join.log.txt.gz)).  I ran on 8/cores 32Gigs in about 6min.  Perhaps you ran out of disk or memory?  

The ascii decoding thing looks like it could be an issue where it's failing to handle an earlier error.  If you want to share your whole log, I'll take a look at that -- there might be something more informative outside what you pasted here.

**Comment by ETC100** [comment] 2023-04-26 02:12
> Not to sure what's going on here. I was unable to reproduce (my [log is here](https://github.com/ComparativeGenomicsToolkit/cactus/files/11323036/join.log.txt.gz)). I ran on 8/cores 32Gigs in about 6min. Perhaps you ran out of disk or memory?
> 
> The ascii decoding thing looks like it could be an issue where it's failing to handle an earlier error. If you want to share your whole log, I'll take a look at that -- there might be something more informative outside what you pasted here.

I have share the complete log file through this link (https://drive.google.com/file/d/1jno1j21LtagyaFVrvFQIVGcko6-ZwqzE/view?usp=sharing).  Unfortunately, I ran pipeline for several times and output the log information in the same log. I have removed redundant information and only retained the information related to the above error in the log file, while there may still unnecessary information in it.
Additionally, I found there is no error when I ran: cactus-graphmap-join ./jobstore --vg Result/chrom-alignments/*.vg --hal Result/chrom-alignments/*.hal --outDir Result --outName chicken_graph --reference REF --workDir ./ --vcf --giraffe clip, which gave up filter after "--giraffe" and "filter, clip" after vcf. However, although I can complete vg giraffe and vg pack steps using this graph without error, vg call was very slow and output nothing (it has ran 2 weeks). I have tried to deliver "--min-lenghth 50", "-c 50" and use 30 cores, but these parameters did not work and the vg call was still slow.

**Comment by glennhickey** [comment] 2023-04-26 14:33
I wish I could reproduce this.  Even though the error's coming from Python's `decode` it's hard to believe that's the issue, since similar commands are succeeding for you.  So it really seems to be related to `vg clip -d 2` (which is making the filter graph). But if that were crashing, even in the chain of commands, I would expect some kind of message in the log.   Out of curiosity, what do you get when you run `vg --version` ?

**Comment by ETC100** [comment] 2023-04-27 04:20
> I wish I could reproduce this. Even though the error's coming from Python's `decode` it's hard to believe that's the issue, since similar commands are succeeding for you. So it really seems to be related to `vg clip -d 2` (which is making the filter graph). But if that were crashing, even in the chain of commands, I would expect some kind of message in the log. Out of curiosity, what do you get when you run `vg --version` ?

I got version information like this: vg: variation graph tool, version v1.47.0-35-g36af48e47 "Ostuni", which was originally packed into cactus 2.5.1.

**Comment by glennhickey** [comment] 2023-04-27 17:47
If you want, I've attached a patch you can try:
[cactus_graphmap_join.py.gz](https://github.com/ComparativeGenomicsToolkit/cactus/files/11346510/cactus_graphmap_join.py.gz)

 It replaces the failing `vg clip | vg clip | vg clip` command with three separate calls.  The hope is that in doing so, it can tell you which one is failing and maybe give a more informative error.  

To use it, you would download and uncompress it, then replace it in the virtualenv you installed cactus in, then rerun `cactus-graphmap-join` from scratch.  

To find the file to replace, you can do something like 
```
find ./cactus-venv-v2.5.1/ -name "cactus_graphmap_join.py"
./cactus-venv-v2.5.1/lib/python3.9/site-packages/cactus/refmap/cactus_graphmap_join.py
```

**Comment by ETC100** [comment] 2023-04-29 08:35
> If you want, I've attached a patch you can try: [cactus_graphmap_join.py.gz](https://github.com/ComparativeGenomicsToolkit/cactus/files/11346510/cactus_graphmap_join.py.gz)
> 
> It replaces the failing `vg clip | vg clip | vg clip` command with three separate calls. The hope is that in doing so, it can tell you which one is failing and maybe give a more informative error.
> 
> To use it, you would download and uncompress it, then replace it in the virtualenv you installed cactus in, then rerun `cactus-graphmap-join` from scratch.
> 
> To find the file to replace, you can do something like
> 
> ```
> find ./cactus-venv-v2.5.1/ -name "cactus_graphmap_join.py"
> ./cactus-venv-v2.5.1/lib/python3.9/site-packages/cactus/refmap/cactus_graphmap_join.py
> ```

I have used the new cactus_graph_join.py to replace the previous one. I got the new log file and reported error with command "cactus-graphmap-join ./jobstore --vg Result/chrom-alignments/.vg --hal Result/chrom-alignments/.hal --outDir Result --outName species_graph --reference REF --workDir ./ --vcf clip filter --giraffe clip filter"(https://drive.google.com/file/d/1hfTasLxXBqId1JZKuNVjWw2lWd2X_yFr/view?usp=sharing).

**Comment by glennhickey** [comment] 2023-05-01 15:49
So the same error..  I'm not really sure how to proceed.  Either there's a glaring bug and I'm not reproducing it because I'm running on a small subset (whereas you're running on all the files)? This seems unlikely since the individual contigs are treated independently.  Or maybe there's an issue with the byte encoding that's only coming up for your Python and nobody else's?  Seems possible, but hard for me to address without reproducing.  But if that is the case, maybe you can try using the Docker release?  It ships with its own Python and at least any errors you get I should be able to reproduce...

**Comment by glennhickey** [comment] 2023-05-02 13:37
Good news: I ran into this same error (though in a different command) while debugging something else.  So there's hope for a fix soon.

**Comment by glennhickey** [comment] 2023-05-15 21:08
This crash is fixed in the latest release.  

That's not to say your workflow will run through, but you will at least get a sensible error.

**Closed** 2023-06-13 15:47 UTC
